# -*- coding: utf-8 -*-
"""trabalho-ML

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A1FlkZm483crEjM5qIzQp3luj6mEEijm
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import OrdinalEncoder
import matplotlib.pyplot as plt

dataframe = pd.read_csv('Software_Salary.csv')
dataframe

# Conversão das variáveis categóricas
encoder_company = OrdinalEncoder()
encoder_title = OrdinalEncoder()
encoder_location = OrdinalEncoder()
encoder_employment = OrdinalEncoder()
encoder_roles = OrdinalEncoder()

# Realizando conversão
dataframe['Employment Status'] = encoder_employment.fit_transform(dataframe['Employment Status'].values.reshape(-1,1))
dataframe['Job Roles'] = encoder_roles.fit_transform(dataframe['Job Roles'].values.reshape(-1,1))

dataframe = dataframe.dropna()

# Dividindo os dados em x (input) e y (output)
x = dataframe.drop(['Rating', 'Company Name', 'Job Title', 'Salaries Reported', 'Location'], axis=1)
y = dataframe['Salary']

x, y

# Separanndo os dados em treinno e teste
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3,
                                                     random_state=42)

x_train, y_train

x_test, y_test